version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install requests mock pytest
      - run:
          command: |
            . venv/bin/activate
            pytest -s -v
      - store_artifacts:
          path: .pytest_cache
          destination: .pytest_cache
  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
      - run:
          name: init .pypirc
          command: |
            echo -e "[distutils]" >> ~/.pypirc
            echo -e "index-servers =" >> ~/.pypirc
            echo -e "  pypi" >> ~/.pypirc
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository=https://pypi.python.org/pypi" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            . venv/bin/activate
            python setup.py sdist upload -r pypi
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master